### PR TITLE
Tell users if IBus Daemon is not running

### LINKED ISSUE #17: Segfaults when clicked if no iBus
The indicator segfaults when clicked on if IBus is not running, which causes wingpanel to stay dead if clicked again after cerbere restarts it.

### PR DESCRIPTION
**Pull request by ryonakano**
Screenshot from 2020-10-21 22-17-14

Fixes #17

- [x] Update the visible view on open

### CODE REVIEW

**Comment by fabiozaramella** [comment]
Hey, I know this is still a wip but maybe "N/A" should be marked as translatable (for example in italian it would be "N.D." and and in french "S.O." i think). 😅 How would it be translated in japanese just out of curiosity, would it remain N/D from english or something like 無し?

**Comment by ryonakano** [comment]
Oh, I didn't know that it is translated in some languages! Will fix it. 👍 

> How would it be translated in japanese just out of curiosity, would it remain N/D from english or something like 無し?

Hmm it would be contextual but I often remain as it is. If it's not descriptive enough I would translate it something like "無し" as you said or "利用不可" because "N/A" is short for "not available".

I'm glad you study Japanese! ☺️

**Comment by fabiozaramella** [comment]
> Oh, I didn't know that it is translated in some languages! Will fix it. 👍

Just make sure to add a note to translators who may not immediately understand where this string belongs to in the UI. 😉👍🏻

> Hmm it would be contextual but I often remain as it is. If it's not descriptive enough I would translate it something like "無し" as you said or "利用不可" because "N/A" is short for "not available".

"利用不可" sounds good to me, more clear than "無し" maybe. I don't know if it would look too long and verbose in the the context of the panel but i don't think so. 

> I'm glad you study Japanese! ☺️

ありがとうございます！実は四年間勉強していましたよ。☺️

**Comment by ryonakano** [comment]
> I don't know if it would look too long and verbose in the the context of the panel but i don't think so.

Yeah I also thought about that… might be better to keep "N/A" in Japanese too.

> ありがとうございます！実は四年間勉強していましたよ。:relaxed:

4年間！　すごいですね…!! :open_mouth:

**Comment by fabiozaramella** [comment]
> Yeah I also thought about that… might be better to keep "N/A" in Japanese too.

Maybe try with "利用不可" first, using your own language is always better (when possible) than taking from english 😉 at least while there is enough free space in the panel.

**Comment by fabiozaramella** [comment]
I'm obviously in favor of showing an advice that IBus Daemon is not currently running but I also have to point out some notes on this.

First of all the popover gets really really big, much bigger than in your first screenshot and i think it should be smaller. 

Schermata del 2020-10-26 10 19 06

Second (this may require another PR, tell me if you want me to report them as separate bugs) once the deamon is started the indicator only display the link for settings and not the selection betweeninput methods. Third, the icons shown is always incorrect, for example moz is shown correctly but when i switch to Italian the icon show "xb".

**Comment by ryonakano** [comment]
> First of all the popover gets really really big, much bigger than in your first screenshot and i think it should be smaller.

Yeah you're right, I changed the text to make it more clear when users clicked the bottom button but it was too long :sweat_smile:

> Second (this may require another PR, tell me if you want me to report them as separate bugs) once the deamon is started the indicator only display the link for settings and not the selection betweeninput methods.

Hmm, it looks like initializing engines list fails if ibus-daemon is not running when the wingpanel starts. This may be in the scope of this PR, I'll take a look.

> Third, the icons shown is always incorrect, for example moz is shown correctly but when i switch to Italian the icon show "xb".

This seems to be because the Italian keyboard seem to have a prefix "xkb". I think the icon should be "it" but this would be out of scope for this PR, so would you file an issue for this?

**Comment by ryonakano** [comment]
Fixed first and second suggestions.

**Comment by ryonakano** [comment]
Another issue related to this PR is that the icon does not change to "N/A" even if you *killall* ibus-daemon:

Screenshot from 2020-10-27 09-18-11

I'll take a look at this soon.

**Comment by ryonakano** [comment]
Fixed the issue in the comment above.

**Comment by fabiozaramella** [comment]
Great! Sorry for the delay on this, I've been pretty busy. I'll try to take a look at this tonight or tomorrow. 😊👍🏻

**Review by fabiozaramella — APPROVED** [review]
Looks good to me👍🏽️  Thank you for your work! 😊️

I'll file a bug report for the icon not reflecting the actual language, though.

**Pull request merged**
